server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: internship-management

  datasource:
    url: jdbc:mysql://localhost:3306/internship_management?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: h5studiogl@gmail.com
    password: ubqq hfra cduj tlnq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# JWT Configuration
jwt:
  secret: dGhpc0lzQVZlcnlTZWN1cmVTZWNyZXRLZXlGb3JKV1RIUzUxMkFsZ29yaXRobVRoYXRJc0F0TGVhc3Q1MTJCaXRzTG9uZ0FuZFNob3VsZFdvcmtQZXJmZWN0bHlGb3JPdXJTcHJpbmdCb290QXBwbGljYXRpb24=
  expiration: 86400000 # 24 hours in milliseconds

# Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# Logging
logging:
  level:
    com.internship: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# File storage
file:
  upload-dir: ./uploads
