spring:
  application:
    name: internship-management-test
  
  main:
    allow-bean-definition-overriding: true
  
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    defer-datasource-initialization: true
    
  h2:
    console:
      enabled: true
      
  sql:
    init:
      mode: always
      
# JWT Configuration for testing
app:
  jwt:
    secret: mySecretKey
    expiration: 86400
    
# Server Configuration
server:
  port: 0

# Logging
logging:
  level:
    com.internship: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG 